package com.educationerp.document.storage;

import java.io.IOException;
import java.io.InputStream;

/**
 * Where the bytes live.
 *
 * <p>The database holds metadata, checksums and a key; it never holds a file. Keeping that
 * behind an interface means the school can start on a disk and move to object storage later
 * without the document service noticing, and it means the version history and the access rules
 * are written once rather than twice.
 *
 * <p>A key is opaque to callers: generated by the storage service, never assembled from a
 * filename a user typed.
 */
public interface ObjectStorage {

    /** Recorded on every document, so a row still says where its bytes are. */
    String provider();

    /** Write the stream under the key, replacing anything already there. */
    void put(String key, InputStream content) throws IOException;

    /** Read the bytes back. The caller closes the stream. */
    InputStream open(String key) throws IOException;

    void delete(String key) throws IOException;

    boolean exists(String key);

    /** Bytes actually stored, which may disagree with what the caller said they were sending. */
    long size(String key);
}
