import { chromium } from 'playwright'
const BASE = 'http://localhost:5173'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: 1400 } })
await p.goto(BASE, { waitUntil: 'networkidle' })
await p.getByLabel(/username or email/i).fill('admin')
await p.getByLabel(/password/i).fill('Institution123!')
await p.getByRole('button', { name: 'Sign in' }).click()
await p.getByRole('button', { name: 'Sign out' }).waitFor({ timeout: 20000 })
await p.goto(`${BASE}/library`, { waitUntil: 'networkidle' })
await p.getByRole('tab', { name: 'Circulation', exact: true }).click()
await p.waitForTimeout(2000)
await p.locator('select').filter({ has: p.locator('option', { hasText: 'MBR-' }) }).first().selectOption({ label: 'Lend Test 040108 (MBR-00007)' })
await p.waitForTimeout(2000)
console.log('=== circulation ===')
console.log(await p.locator('main').innerText())
console.log('=== headers ===')
console.log(await p.locator('th').allTextContents())
console.log('=== row0 ===')
console.log(await p.locator('tbody tr').first().innerText())
console.log('=== buttons in row0 ===')
console.log(await p.locator('tbody tr').first().getByRole('button').allTextContents())
await b.close()
