package com.educationerp.auth.permission;

/**
 * Granular permission catalogue. Values are stable strings stored in the database so
 * custom roles can be composed later without code changes.
 */
public enum Permission {

    // Institution & configuration
    INSTITUTION_READ,
    INSTITUTION_UPDATE,
    MODULE_CONFIG_READ,
    MODULE_CONFIG_UPDATE,
    SETTINGS_READ,
    SETTINGS_UPDATE,
    AUDIT_READ,

    // Users, roles
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    USER_RESET_PASSWORD,
    ROLE_READ,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,
    PERMISSION_READ,
    PERMISSION_ASSIGN,

    // Academic structure
    ACADEMIC_READ,
    ACADEMIC_CREATE,
    ACADEMIC_UPDATE,
    ACADEMIC_DELETE,
    CURRICULUM_READ,
    CURRICULUM_UPDATE,
    TIMETABLE_READ,
    TIMETABLE_MANAGE,
    CALENDAR_READ,
    CALENDAR_MANAGE,
    ROOM_MANAGE,

    // Admission
    ADMISSION_READ,
    ADMISSION_CREATE,
    ADMISSION_UPDATE,
    ADMISSION_REVIEW,
    ADMISSION_APPROVE,
    ADMISSION_REJECT,
    ADMISSION_OFFER,
    CAMPAIGN_MANAGE,
    APPLICATION_DOCUMENT_REVIEW,

    // Students
    STUDENT_READ,
    STUDENT_CREATE,
    STUDENT_UPDATE,
    STUDENT_DELETE,
    STUDENT_STATUS_CHANGE,
    ENROLLMENT_READ,
    ENROLLMENT_CREATE,
    ENROLLMENT_UPDATE,
    ENROLLMENT_DELETE,
    GUARDIAN_READ,
    GUARDIAN_MANAGE,
    GRADUATION_READ,
    GRADUATION_MANAGE,

    // Attendance
    ATTENDANCE_READ,
    ATTENDANCE_MARK,
    ATTENDANCE_APPROVE,
    ATTENDANCE_CORRECT,

    // Examination
    EXAM_READ,
    EXAM_CREATE,
    EXAM_SCHEDULE_MANAGE,
    EXAM_ELIGIBILITY_MANAGE,
    MARKS_ENTER,
    MARKS_VERIFY,
    MARKS_APPROVE,
    RESULT_PUBLISH,
    RESULT_CORRECT,
    RESULT_READ,
    REPORT_CARD_READ,
    REPORT_CARD_GENERATE,
    TRANSCRIPT_READ,
    TRANSCRIPT_GENERATE,
    CERTIFICATE_READ,
    CERTIFICATE_GENERATE,

    // Grading
    GRADING_READ,
    GRADING_MANAGE,

    // Finance
    FEE_READ,
    FEE_CREATE,
    FEE_APPROVE,
    INVOICE_READ,
    INVOICE_CREATE,
    PAYMENT_READ,
    PAYMENT_CREATE,
    PAYMENT_REFUND,
    DISCOUNT_READ,
    DISCOUNT_MANAGE,
    SCHOLARSHIP_READ,
    SCHOLARSHIP_MANAGE,
    FINANCE_REPORT_READ,

    // Accounting
    ACCOUNTING_READ,
    ACCOUNTING_POST,
    ACCOUNTING_MANAGE,
    LEDGER_READ,
    RECONCILIATION_MANAGE,

    // HR
    EMPLOYEE_READ,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE,
    LEAVE_READ,
    LEAVE_APPROVE,
    LEAVE_APPLY,
    ATTENDANCE_EMPLOYEE_READ,
    ATTENDANCE_EMPLOYEE_MARK,
    PAYROLL_READ,
    PAYROLL_PROCESS,
    PAYROLL_APPROVE,
    PAYSLIP_READ,
    SALARY_MANAGE,

    // Library
    LIBRARY_READ,
    LIBRARY_MANAGE,
    LIBRARY_CIRCULATE,

    // Inventory
    INVENTORY_READ,
    INVENTORY_MANAGE,
    INVENTORY_TRANSACT,

    // Assets
    ASSET_READ,
    ASSET_MANAGE,

    // Documents
    DOCUMENT_READ,
    DOCUMENT_UPLOAD,
    DOCUMENT_VERIFY,
    DOCUMENT_DELETE,

    // Communication
    COMMUNICATION_READ,
    COMMUNICATION_SEND,
    TEMPLATE_READ,
    TEMPLATE_MANAGE,
    NOTICE_PUBLISH,

    // Portals & self-service
    PORTAL_STUDENT,
    PORTAL_PARENT,
    PORTAL_TEACHER,
    SELF_PROFILE_UPDATE,

    // Reporting / imports / search
    REPORT_READ,
    REPORT_EXPORT,
    IMPORT_READ,
    IMPORT_RUN,
    SEARCH_GLOBAL,

    // Dashboards
    DASHBOARD_ADMIN,
    DASHBOARD_PRINCIPAL,
    DASHBOARD_ACCOUNTANT,
    DASHBOARD_TEACHER,
    DASHBOARD_STUDENT,
    DASHBOARD_PARENT
}
